# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1305, 1020)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_edit_image_path = QtWidgets.QLineEdit(self.centralWidget)
        self.line_edit_image_path.setReadOnly(True)
        self.line_edit_image_path.setObjectName("line_edit_image_path")
        self.horizontalLayout.addWidget(self.line_edit_image_path)
        self.button_open_image = QtWidgets.QPushButton(self.centralWidget)
        self.button_open_image.setObjectName("button_open_image")
        self.horizontalLayout.addWidget(self.button_open_image)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_edit_docstring = QtWidgets.QTextEdit(self.groupBox_2)
        self.text_edit_docstring.setReadOnly(True)
        self.text_edit_docstring.setObjectName("text_edit_docstring")
        self.verticalLayout_3.addWidget(self.text_edit_docstring)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.transforms_tree = QtWidgets.QTreeView(self.centralWidget)
        self.transforms_tree.setObjectName("transforms_tree")
        self.verticalLayout_2.addWidget(self.transforms_tree)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_clear = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear.sizePolicy().hasHeightForWidth())
        self.button_clear.setSizePolicy(sizePolicy)
        self.button_clear.setObjectName("button_clear")
        self.horizontalLayout_4.addWidget(self.button_clear)
        self.button_update_image = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_update_image.sizePolicy().hasHeightForWidth())
        self.button_update_image.setSizePolicy(sizePolicy)
        self.button_update_image.setObjectName("button_update_image")
        self.horizontalLayout_4.addWidget(self.button_update_image)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.list_widget_selected_transforms = QtWidgets.QListWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_widget_selected_transforms.sizePolicy().hasHeightForWidth())
        self.list_widget_selected_transforms.setSizePolicy(sizePolicy)
        self.list_widget_selected_transforms.setMaximumSize(QtCore.QSize(200, 16777215))
        self.list_widget_selected_transforms.setObjectName("list_widget_selected_transforms")
        self.verticalLayout_4.addWidget(self.list_widget_selected_transforms)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.transform_params_layout = QtWidgets.QVBoxLayout(self.groupBox)
        self.transform_params_layout.setContentsMargins(11, 11, 11, 11)
        self.transform_params_layout.setSpacing(6)
        self.transform_params_layout.setObjectName("transform_params_layout")
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 647, 965))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.horizontalLayout_3.addWidget(self.label_image)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2.setStretch(3, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_open_image.setText(_translate("MainWindow", "Open"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Doscstring"))
        self.label.setText(_translate("MainWindow", "Selected transforms"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))
        self.button_update_image.setText(_translate("MainWindow", "Update image"))
        self.groupBox.setTitle(_translate("MainWindow", "Transform params"))
        self.label_image.setText(_translate("MainWindow", "Empty Image"))

